export const GAPI_UPDATE_STATUS = 'GAPI_UPDATE_STATUS';
export const GAPI_TOGGLE_AUTH = 'GAPI_TOGGLE_AUTH';
export const GAPI_REAUTH = 'GAPI_TOGGLE_AUTH';
export const GAPI_REVOKE = 'GAPI_REVOKE';
export const MEMBER_DATA_LOADED = 'MEMBER_DATA_LOADED';
